FROM python:3.9.7-slim

# Ensure the pip version is latest as for some packages it's important to use latest version
RUN pip install -U pip
RUN pip install pipenv 

# Specify working direcory inside the Docker container and copy all files there
WORKDIR /app

# Copy both Pipfile and Pipfile.lock into the current directory (./)
COPY [ "Pipfile", "Pipfile.lock", "./" ]

# Install all dependencies using Pipfiles, skip creating virtual env using --system since it's in a Docker container (already isolated)
# --deploy fails a build if the Pipfile.lock is outdated (does not match Pipfile) instead of creating a new one.
RUN pipenv install --system --deploy

# Copy model
COPY [ "predict.py", "lin_reg.bin", "./" ]

# Informs the port number used in the Flask app, meant for documentation purpose.
EXPOSE 9696

# Sets the executable program each time this container is started
ENTRYPOINT [ "gunicorn", "--bind=0.0.0.0:9696", "predict:app" ]