{
 "title": "NYC taxi feb dashboard",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-28T23:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction Drifts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "    SELECT\n    $__time(timestamp),\n    prediction_drift\n    FROM dummy_metrics \n    WHERE $__timeFilter(timestamp)\n    ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Num of Drifted Columns",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "    SELECT\n    $__time(timestamp),\n    num_drifted_columns\n    FROM dummy_metrics \n    WHERE $__timeFilter(timestamp)\n    ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Missing Values by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "    SELECT\n    $__time(timestamp),\n    share_missing_values\n    FROM dummy_metrics \n    WHERE $__timeFilter(timestamp)\n    ORDER BY timestamp"
    }
   ]
  }
 ]
}